### ISSUE TITLE
Bogus `1.0.0` chart release on https://helm.openwebui.com/index.yaml

### ISSUE THREAD

**Issue by rpardini** [open-webui/helm-charts#107]
https://helm.openwebui.com/index.yaml lists 1.0.0, but then https://helm.openwebui.com/open-webui-1.0.0.tgz doesn't exist.

That only started to happen around 16 hours ago.

So I suppose some oopsie happened, and possibly the index has to be regenerated?

**Comment by 0xThresh** [comment]
Thanks for the heads up @rpardini. I had rolled out a new semantic versioning release action that didn't work as expected, and it appears that I deleted the bad chart versions without fixing the index. I've removed the bad versions from the index, hopefully that will help fix it.

**Comment by rpardini** [comment]
Fixed. Thanks!
