### ISSUE TITLE
[Question] Update syncing to otwld/ollama-helm?

### ISSUE THREAD

**Issue by malcolmlewis** [open-webui/helm-charts#20]
Hi, there are a number of Nvidia GPU updates in the latest otwld/ollama-helm chart
App version: 0.1.38
Chart version: 0.29.1

If I do a fresh deployment on the open-webui chart, should these get pulled, or does the chart need updating?

**Comment by 0xThresh** [comment]
Hey @robrakaric, could use your help understanding the behavior for the embedded Ollama chart. 

I see that the Chart.yaml file pulls versions of the Ollama chart that are greater than version 0.24.0: https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/Chart.yaml#L27

I also see that we have version v0.25.0 embedded in `charts`: https://github.com/open-webui/helm-charts/tree/main/charts/open-webui/charts

Do you know offhand whether the OWUI Helm chart pull the latest chart on a new build, or if it pulls the embedded 0.25.0 chart we have in the repo?

**Comment by malcolmlewis** [comment]
@0xThresh Hi, I see;
```bash
Labels:              app.kubernetes.io/component=ollama                                                                                                                                    │
│                      app.kubernetes.io/instance=open-webui                                                                                                                                 │
│                      app.kubernetes.io/managed-by=Helm                                                                                                                                     │
│                      app.kubernetes.io/version=0.1.34                                                                                                                                      │
│                      helm.sh/chart=ollama-0.25.0                                                                                                                                           │
│                      pod-template-hash=56c55f7c6
```

**Comment by robrakaric** [comment]
@0xThresh good question. I'd have to do some testing.

What I'm not sure of is `chart-releaser`'s behavior. The assets in the gh release will be most relevant, and I'm not sure if `chart-releaser` actually downloads the newest version (`helm dependency update`), uses the one in the repo, or just respects what's in `Chart.lock` (`helm dependency build`).

I'll mess around with in on my fork and see what I can find out.

**Comment by 0xThresh** [comment]
We have a PR open that should get merged whenever Tim takes a look at it, so we can also observe the behavior there once we pull that in. Thanks for taking a look!

**Comment by 0xThresh** [comment]
The latest Ollama chart is bundled into the new Open WebUI charts 🎉
