### ISSUE TITLE
feat: Allow optional clusterIP and loadBalancerIP fields on the service

### ISSUE THREAD

**Issue by pranay-jain-notable** [open-webui/helm-charts#32]
### Feature Request

Currently the chart lacks the ability to specify the IP address that one may want to host the open-webui service. As a result, the service is served on a randomly selected IP address. This prevents any applications where one may want to host the service at a static IP address.

The `service.yaml` template should allow users to optionally specify the `loadBalancerIP` and the `clusterIP` for the `loadBalancer` and `clusterIP` type services respectively.  

I have implemented this functionality in a local fork of the chart and would be happy to make a pull request on this repo for the same.

**Comment by 0xThresh** [comment]
Hi @pranay-jain-notable, PRs are definitely welcome if you already have it fixed locally. I'd be happy to test it out and merge it if all looks good!

**Comment by pranay-jain-notable** [comment]
I've posted Pull Request #37 for this feature. As mentioned, I've tested this out locally and on a production kubernetes cluster for the `LoadBalancer` service type.

**Comment by 0xThresh** [comment]
Merged, thanks again!
