### ISSUE TITLE
bug: multi attach error for volumes if a pod is restarted on another node of the cluster when persistence is enabled

### ISSUE THREAD

**Issue by matthieucharreire** [open-webui/helm-charts#34]
I have encountered an issue with this chart that I have used to deploy open webui on a kubernetes cluster that has several nodes with persistence enabled.

If a pod is restarted on a new node, there is an error while attaching to a volume (for the `backend/data/` directory) located on the previous node.

I think this could be fix by relying on a `StatefulSet` instead of a `Deployment` to manage open webui pods.

**Comment by 0xThresh** [comment]
PR merged, thanks again!
