### ISSUE TITLE
bug: open-webui statefulset requires serviceName

### ISSUE THREAD

**Issue by patrickstump** [open-webui/helm-charts#40]
Chart: open-webui
Version: 3.0.4

## Problem

When persistence is enabled (default), the workload-manager becomes a statefulset instead of a deployment.
As such, kubernetes requires the `statefulSet.spec.serviceName` key to exist.

See [Creating a StatefulSet](https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/#creating-a-statefulset) for reference, and search for serviceName.

This causes the template to fail installation if persistence is enabled.

**Comment by 0xThresh** [comment]
Fixed in https://github.com/open-webui/helm-charts/pull/41
