### ISSUE TITLE
Update Release to 3.0.8

### ISSUE THREAD

**Issue by whur** [open-webui/helm-charts#42]
Can we get an update on the helm chart to the 3.0.8 release of open-webui? Please and thank you kindly.

**Comment by justinh-rahb** [comment]
The helm repo maintainer is currently on vacation and may be unavailable still.

**Comment by 0xThresh** [comment]
Sorry for the delay on it, I'm in the middle of a long moving process and haven't had time to get the charts updated. I should be able to get an update out in the next week, but if you set the image value to use "latest" in your deployment, you should end up with the newest version of Open WebUI.

**Comment by 0xThresh** [comment]
Also, PR welcome on this if someone wants to try upgrading!

**Comment by whur** [comment]
I had it set to latest, but pinned it to the most recent tagged and that worked! 

I did try to learn by cloning the repo but I couldn't get the index of the helm to work out when trying to update my helm repos. I'm new to this!

**Comment by 0xThresh** [comment]
Chart version is now updated: https://github.com/open-webui/helm-charts/pull/45
