### ISSUE TITLE
Enhancement: Write Chart Tests

### ISSUE THREAD

**Issue by 0xThresh** [open-webui/helm-charts#47]
To make sure updates are stable prior to release, we should add [Chart Tests](https://helm.sh/docs/topics/chart_tests/) to the repo. We can start small and continuously build up to add more of Open WebUI's core functionality.

Basic starting point:
1. Ensure that Open WebUI starts
2. Ensure that Open WebUI pod can communicate with its Ollama URL and Pipelines URL (if applicable)

**Comment by Infinoid** [comment]
Suggestion: make sure `helm lint` passes.
It's not very thorough, but it's easy and it's useful.

**Comment by 0xThresh** [comment]
Great community PR took care of this: https://github.com/open-webui/helm-charts/pull/113
