### ISSUE TITLE
Also publish the chart as an OCI artifact

### ISSUE THREAD

**Issue by chgl** [open-webui/helm-charts#50]
Since Helm 3.8.0 support for storing and using OCI-based registries is enabled by default: https://helm.sh/docs/topics/registries/

Storing the chart as an OCI artifact makes it easier to install and also use as a dependency (no need for a `helm repo add`).

We could use ghcr.io for this and it should only take around 15-20 additional LoC in the workflow: https://github.com/chgl/charts/blob/master/.github/workflows/release.yaml#L48-L68

It's something I could take a stab at if it's a useful addition!

**Comment by 0xThresh** [comment]
Thanks @chgl, definitely happy to look at a PR on this if you want to try it out!
