### ISSUE TITLE
How to add custom dependencies?

### ISSUE THREAD

**Issue by sir3mat** [open-webui/helm-charts#56]
Hi, i would like to develop a pipeline for tracing using phoenix or mlflow. How can i add custom dependencies with the helm chart? I need to package a dedicate images starting from the pipeline image or there are different approaches?

**Comment by 0xThresh** [comment]
Hi @sir3mat, when you add the dependencies to the beginning comment of your pipeline code, it should pull the dependencies automatically when the new pipeline is added to your Open WebUI server. Here's an example from one of my Pipelines:

```
"""
title: Llama Index DB Pipeline
author: 0xThresh
date: 2024-07-01
version: 1.0
license: MIT
description: A pipeline for using text-to-SQL for retrieving relevant information from a database using the Llama Index library.
requirements: llama_index, sqlalchemy, psycopg2-binary
"""
```
So you'd add your required packages into the `requirements` line in your pipeline code, and the Pipelines server should pull those automatically. You shouldn't need to do anything in Helm unless you decide to package your own Pipelines container with the dependencies pre-installed, at which point you'd just update the Pipelines image value. 

If you have issues using the `requirements` line in your pipeline code, you're probably better off opening an issue in the [Pipelines repository](https://github.com/open-webui/pipelines/issues).
