### ISSUE TITLE
Enhancement: Add imagePullSecrets or ServiceAccount to pipeline deployments

### ISSUE THREAD

**Issue by marlapativ** [open-webui/helm-charts#59]
Is your feature request related to a problem? Please describe.
- I'm trying to bake a new image with my custom pipeline and requirements setup
   I didn't want to volume mount my requirements and pass the variables.
   I am updating the existing image with my requirements and am pushing the image to private registry

Describe the solution you'd like

1. Add imagePullSecrets to deployments (or)
2. Add a serviceaccount and set pull secrets to service account

Describe alternatives you've considered
No option but to fork and add my customizations to these charts

Additional context
-

**Comment by 0xThresh** [comment]
Thanks for submitting @marlapativ, I can take a look at adding these in the coming days, but PRs are welcome if you end up solving this for your Open WebUI deployment.

**Comment by marlapativ** [comment]
@0xThresh, I've raised a PR, please review and merge if it looks good.
