### ISSUE TITLE
Failed to fetch open-webui helm chart

### ISSUE THREAD

**Issue by stepanbaghdasaryan** [open-webui/helm-charts#6]
**Problem:**
When attempting to download the Helm chart from open-webui, an error occurs. The error message is:

```log
Error: failed to fetch https://helm.openwebui.com/open-webui-1.0.0.tgz : 404 Not Found
```

**Steps to Reproduce:**

1. Execute the following commands to reproduce the issue:

```bash
helm repo add open-webui https://helm.openwebui.com/
helm repo update
helm pull open-webui/open-webui
```

**Expected Behavior:**
The Helm chart should be successfully downloaded without encountering a 404 error.

**Additional Information:**

Helm Version: [v3.14.4]

**Comment by 0xThresh** [comment]
Thanks for submitting, we noticed this issue last night but forgot to submit an issue for it. I'm hoping this PR will solve it: https://github.com/open-webui/helm-charts/pull/7

**Comment by robrakaric** [comment]
> Thanks for submitting, we noticed this issue last night but forgot to submit an issue for it. I'm hoping this PR will solve it: #7

#8 solved it! @stepanbaghdasaryan , if you do a `helm repo update` now, you should be able to pull version `1.0.1` of the chart properly.

**Comment by stepanbaghdasaryan** [comment]
yeap, perfect, it works!
