### ISSUE TITLE
How to setup customised prompt suggestions

### ISSUE THREAD

**Issue by Soap2G** [open-webui/helm-charts#71]
I'm trying to setup a customised set of prompt suggestions in my k8s deployment.
I see that in the [`config.py`](https://github.com/open-webui/open-webui/blob/f4df49e600a36ea1616f4d0dc6e5c748fc4dbb74/backend/config.py#L130) there's the `DEFAULT_CONFIG` variable that provides those prompts. Also [this](https://github.com/open-webui/open-webui/blob/f4df49e600a36ea1616f4d0dc6e5c748fc4dbb74/backend/config.py#L721) does the same?

I'm wondering if there's a way to setup custom prompts that are able to hold even when a Helm upgrade is triggered.

Thanks a lot

EDIT: Clarify issue

**Comment by Soap2G** [comment]
Summoning @0xThresh

**Comment by 0xThresh** [comment]
Hey @Soap2G, I heard from other maintainers that on the latest versions of Open WebUI, the custom prompts are stored in the config database. That should mean that if you use a PVC and add the custom prompts, they should persist through an upgrade.

If you've seen different behavior please let me know so we can figure out what's causing the issue.

**Comment by Soap2G** [comment]
Hi @0xThresh, thanks a lot for the insights! Here are a couple of additional questions:
1. We use a db on demand service, so if the config database is not a separate instance but leverages the DATABASE_URL, we should have a persistent resource already. However, I didn't see any `config` db created in the instance, even after the customisation fo the prompts via the dashboard. 
    - If there's an additional config db being created locally, I missed that.
3. I opened this issue because among the issue per se, I also wanted to understand if a declarative approach is possible, just like one does with the `TITLE_GENERATION_PROMPT_TEMPLATE` env var. I.e. without passing through the dashboard and manually change the entries.

Thanks a lot!

**Comment by 0xThresh** [comment]
> However, I didn't see any config db created in the instance, even after the customisation fo the prompts via the dashboard. If there's an additional config db being created locally, I missed that.
For your remote database, it sounds like `config` is a table with a single record with the JSON of the config. My apologies for stating that it was a separate database, it sounds like it should just be a separate table. I haven't had a chance to upgrade versions for a while, so I'm behind the times 😅

> I also wanted to understand if a declarative approach is possible, just like one does with the TITLE_GENERATION_PROMPT_TEMPLATE env var. I.e. without passing through the dashboard and manually change the entries. 
The `extraEnvVars` value is used to pass any extra environment variables that are used in Open WebUI to the pod you create with Helm. If you don't already see a way to generate custom prompts with an environment variable for Open WebUI, you'd want to open an issue on the main repo (https://github.com/open-webui/open-webui) instead.

**Comment by 0xThresh** [comment]
Hey @Soap2G any further actions on this issue, or are we good to close?

**Comment by Soap2G** [comment]
HI @0xThresh, thanks a lot for the insights, and sorry for the delay. We can close, I'll open an issue to the main repo. Thanks again!
