### ISSUE TITLE
Postgres for persistence storage

### ISSUE THREAD

**Issue by hongbo-miao** [open-webui/helm-charts#83]
It seems this pull request allows using Postgres for Open WebUI storage

- https://github.com/open-webui/open-webui/pull/1791

It would be great to support / document as well, thank you! ☺️

**Comment by 0xThresh** [comment]
Hey @hongbo-miao, I believe all you would need to do is add your Postgres connection string as a value to `extraEnvVars`, such as:
```
extraEnvVars:
- name: "DATABASE_URL"
  value: "postgresql://[user[:password]@][host][:port][/dbname][?param1=value1&...]"
```

You can see more in the Open WebUI docs here: https://docs.openwebui.com/getting-started/env-configuration/#database_url

Please report back on whether or not this works for you, thanks!

**Comment by hongbo-miao** [comment]
Thanks @0xThresh ! I assume I could set

```yaml
persistence:
  enabled: false
```

And fully use Postgres to save all data? I will give it a try soon, thanks!

**Comment by tjbck** [comment]
@hongbo-miao yes

**Comment by hongbo-miao** [comment]
Thanks @tjbck for the info! 😃 It makes sense.
So I assume I still have to use Kubernetes persistence storage for uploaded files.
In future, if it could support S3 as storage, that would be awesome! I opened a  feature request at https://github.com/open-webui/open-webui/issues/5763
I will close this for now. Once Open WebUI supports S3 for user uploaded files, I will test Postgres + S3. Thanks!
