### ISSUE TITLE
ENABLE_OLLAMA_API being set to false if ollama.enabled is false

### ISSUE THREAD

**Issue by thaynes43** [open-webui/helm-charts#86]
I don't want Ollama automatically installed but I still want to set a base URL and have the API enabled. 

A change went into the 3.1.x version of the chart that sets ENABLE_OLLAMA_API  to false if ollama.enabled is false. The commit message seems to imply the opposite though, https://github.com/open-webui/helm-charts/commit/2062a5d4e67ca27919c58875bb69579e8fa42906 but it is not setting the URL if Ollama isn't set to be automatically deployed. See this comment https://github.com/open-webui/helm-charts/blob/main/charts/open-webui/values.yaml#L4 for how enabling ollama is to deploy it vs. just to use the API.

Rolling the chart back to `3.1.18` fixes this for me. I am unable to go up to `3.2.x` because my ODIC log in stops working after the change to config maps but since this issue was introduced first (and looks to be copied into the ConfigMap change) I'll look more into that after this.

Thanks!

**Comment by 0xThresh** [comment]
Thanks for the report @thaynes43, that's definitely an oversight. I'll have time to fix this over the weekend, PR welcome if you want to beat me to it though. Thank you!

**Comment by davizucon** [comment]
Hey @thaynes43, you are right, need to take into account that you still can use API the without deploying it.
Looks like #88, fix both OIDC and OLLAMA URL. I'm following this one. 


p.s.: @0xThresh, feel free to tag me, I'll take a look right away.

Thanks!
