### ISSUE TITLE
How to set different key for Pipelines?

### ISSUE THREAD

**Issue by hongbo-miao** [open-webui/helm-charts#89]
I saw default key to talk to Pipelines is `0p3n-w3bu!` based on https://github.com/open-webui/pipelines?tab=readme-ov-file#-quick-start-with-docker

Any env / secret field we can pass to set a different keys? Thanks! ☺️

**Comment by hongbo-miao** [comment]
Thanks @ja14000 ! The one you shared is the password set on Open WebUI side that used to talk to Pipelines. However, I am hoping to change Pipelines default password.

**Comment by justbert** [comment]
You just need to set the [`PIPELINES_API_KEY`](https://github.com/open-webui/pipelines/blob/1136b83d7fab33e46fab1d9c217e2b8ec69796b8/config.py#L14) environment variable. You can create a secret and mount it here: https://github.com/open-webui/helm-charts/blob/645edec6992783881ca9ef7b309e0793a1574e36/charts/pipelines/values.yaml#L60

**Comment by hongbo-miao** [comment]
Thank you so much, @justbert ! I think you are correct. I will try and report back when I got time. ☺️

**Comment by hongbo-miao** [comment]
Thank you so much, @justbert ! Confirmed it works! I opened a pull request at https://github.com/open-webui/helm-charts/pull/96 to document it.
